### ISSUE TITLE
Draft 03: Mention Surrogate keys and foreign keys

### ISSUE THREAD

**Issue by sergeyprokhorenko** [uuid6/uuid6-ietf-draft#78]
[Surrogate keys](https://en.wikipedia.org/wiki/Surrogate_key#Definition) are not primary keys in a temporal database. Therefore, it makes sense to mention that the UUIDs described in this specification are good as primary keys and as surrogate keys.

Foreign keys should be mentioned too.

**Comment by fabiolimace** [comment]
I think UUID v6 and v7 can also be useful for [event-driven architectures](https://en.wikipedia.org/wiki/Event-driven_architecture).

For example, an interface called [`EventSource`](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) exists for [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events). The last event ID can be used so that the server only sends events after the given ID. 

Some links about event-driven stuff:

* [HTTP Feeds spec: Event ID](https://github.com/http-feeds/http-feeds#event-id)
* [Event sourcing](https://martinfowler.com/eaaDev/EventSourcing.html)
* [Event stream processing](https://en.wikipedia.org/wiki/Event_stream_processing)
* [Event-driven architectures](https://martinfowler.com/tags/event%20architectures.html)

**Comment by kyzer-davis** [comment]
@sergeyprokhorenko,

The best place to mention this would be part of the [Introduction, section 1, second paragraph, first line](https://uuid6.github.io/uuid6-ietf-draft/#name-introduction)

Current:
```
A specific use case for UUIDs which has gained popularity is as database primary keys
```

Proposed:
```
A specific use case for UUIDs which has gained popularity is as database primary keys, foreign keys and even surrogate keys.
```

Let me know what you think. 

---

@fabiolimace, I saw your similar comment in another thread. I am not opposed to updating text for another use-case; I just don't know where or how to update the text. Point me in the right direction in Draft 03 and I will give it a stab.

**Comment by broofa** [comment]
I'd like to see us err on the side of less verbiage, rather than more.  Do we really need to enumerate all the different flavors of database keys?  Let just remove "primary" from this text.

> A specific use case for UUIDs which has gained popularity is as database ~~primary~~ keys

**Comment by kyzer-davis** [comment]
@broofa, yeah, I was thinking about that approach as well. Abstract it down to "database keys" and leave it at that.
